### ISSUE TITLE
Help for model and usage

### ISSUE THREAD

**Issue by jun-csbio** [programmablebio/saltnpeppr#1]
Dear Sir,

This work is very interesting. Our group want to use it to help for targeting protein-protein interface. However, we have not found the prediction model in your github site. 

P.S., Could you provide the detail steps of the usage of saltnpeppr. What is the format of the inputs.

Best,

Jun Hu

**Comment by garykbrixi** [comment]
Hello, thank you for your interest. We will share model weights, more details on usage, and an example notebook in the near future
