### ISSUE TITLE
TypeError: unhashable type: 'Series'

### ISSUE THREAD

**Issue by abidozic-zrc** [programmablebio/saltnpeppr#3]
In the top scoring section of the SaLT&PepPR code I get "TypeError: ushashable type: "serioes" 
I just commented out the following line and procedeed with the code
peptides_df = peptides_df.sort_values(['Target','Score'],ascending=False).reset_index(drop=True)
Do you have a solution for how to avoid the error?

Additionally, could this code be used instead of your pepprclip code to design new peptides. The pepprclip code was giving me an error while defining Noisy and Strict datasets cvs files.

**Comment by garykbrixi** [comment]
Hello, thank you for your question. I went to reproduce the error but the problematic line has already been removed by my co-author, fixing this error. 

Yes, the code in the notebook is general and could be used to select peptides based on any method which gives a binding score along an entire partner protein sequence.

I am not familiar with the pepprclip model, I have shared your concerns about pepprclip notebook with the authors of that project
